<h1><center>Laboratorio 9: Optimización de modelos 💯</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2024</strong></center>

### **Cuerpo Docente:**

- Profesores: Ignacio Meza, Sebastián Tinoco
- Auxiliar: Eduardo Moya
- Ayudantes: Nicolás Ojeda, Melanie Peña, Valentina Rojas

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Renato Pino
- Nombre de alumno 2: Valentina Abello

### **Link de repositorio de GitHub:** [Repositorio](https://github.com/Renato-98/MDS7202-1)

### Temas a tratar

- Predicción de demanda usando `xgboost`
- Búsqueda del modelo óptimo de clasificación usando `optuna`
- Uso de pipelines.

### Reglas:

- **Grupos de 2 personas**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias.
- Pueden usar cualquer matrial del curso que estimen conveniente.
- Código que no se pueda ejecutar, no será revisado.

### Objetivos principales del laboratorio

- Optimizar modelos usando `optuna`
- Recurrir a técnicas de *prunning*
- Forzar el aprendizaje de relaciones entre variables mediante *constraints*
- Fijar un pipeline con un modelo base que luego se irá optimizando.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

# Importamos librerias útiles

In [ ]:
!pip install -qq xgboost optuna

# El emprendimiento de Fiu

Tras liderar de manera exitosa la implementación de un proyecto de ciencia de datos para caracterizar los datos generados en Santiago 2023, el misterioso corpóreo **Fiu** se anima y decide levantar su propio negocio de consultoría en machine learning. Tras varias e intensas negociaciones, Fiu logra encontrar su *primera chamba*: predecir la demanda (cantidad de venta) de una famosa productora de bebidas de calibre mundial. Al ver el gran potencial y talento que usted ha demostrado en el campo de la ciencia de datos, Fiu lo contrata como data scientist para que forme parte de su nuevo emprendimiento.

Para este laboratorio deben trabajar con los datos `sales.csv` subidos a u-cursos, el cual contiene una muestra de ventas de la empresa para diferentes productos en un determinado tiempo.

Para comenzar, cargue el dataset señalado y visualice a través de un `.head` los atributos que posee el dataset.

<i><p align="center">Fiu siendo felicitado por su excelente desempeño en el proyecto de caracterización de datos</p></i>
<p align="center">
  <img src="https://media-front.elmostrador.cl/2023/09/A_UNO_1506411_2440e.jpg">
</p>

In [ ]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = '/content/drive/MyDrive/Lab_progra_DS/Lab_9/' # Ajustar al path propio
except:
    print('Ignorando conexión drive-colab')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

df = pd.read_csv(path + 'sales.csv')
df.sample(10)

,id,date,city,lat,long,pop,shop,brand,container,capacity,price,quantity
375,383,31/05/12,Patra,38.24444,21.73444,164250,shop_6,adult-cola,glass,500ml,1.33,28775
3488,3540,30/04/15,Patra,38.24444,21.73444,167001,shop_6,gazoza,glass,500ml,0.55,91516
3011,3056,31/10/14,Athens,37.96245,23.68708,668203,shop_3,lemon-boost,glass,500ml,1.18,9846
5498,5588,31/03/17,Athens,37.97945,23.71622,665871,shop_1,gazoza,glass,500ml,0.78,24310
2047,2078,31/12/13,Athens,37.97945,23.71622,671022,shop_1,gazoza,can,330ml,0.30,43629
4557,4624,30/04/16,Patra,38.24444,21.73444,168254,shop_6,lemon-boost,plastic,1.5lt,2.03,28491
5756,5847,31/05/17,Irakleion,35.32787,25.14341,138200,shop_2,gazoza,glass,500ml,0.85,22186
3541,3594,30/04/15,Patra,38.24444,21.73444,167001,shop_6,orange-power,can,330ml,0.56,49715
1773,1798,31/08/13,Patra,38.24444,21.73444,166301,shop_6,orange-power,plastic,1.5lt,2.17,25801
4430,4497,29/02/16,Patra,38.24444,21.73444,168254,shop_6,orange-power,plastic,1.5lt,1.97,21867

**Nota:** Las fechas estan en formato dia-mes-año

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7456 entries, 0 to 7455
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         7456 non-null   int64
 1   date       7456 non-null   object
 2   city       7456 non-null   object
 3   lat        7456 non-null   float64
 4   long       7456 non-null   float64
 5   pop        7456 non-null   int64
 6   shop       7456 non-null   object
 7   brand      7456 non-null   object
 8   container  7456 non-null   object
 9   capacity   7456 non-null   object
 10  price      7456 non-null   float64
 11  quantity   7456 non-null   int64
dtypes: float64(3), int64(3), object(6)
memory usage: 699.1+ KB

In [ ]:
df.describe()

,id,lat,long,pop,price,quantity
count,7456.000000,7456.000000,7456.000000,7456.000000,7456.000000,7456.000000
mean,3784.926770,38.300616,23.270170,355042.733637,1.197193,29408.428380
std,2185.822361,1.650030,1.086592,232336.703020,0.818175,17652.985675
min,0.000000,35.327870,21.734440,134219.000000,0.110000,2953.000000
25%,1889.750000,37.962450,22.417610,141732.000000,0.620000,16572.750000
50%,3783.500000,38.244440,22.930860,257501.500000,0.930000,25294.500000
75%,5682.250000,39.636890,23.716220,665102.000000,1.510000,37699.000000
max,7559.000000,40.643610,25.143410,672130.000000,4.790000,145287.000000

## 1 Generando un Baseline (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/O-lan6TkadUAAAAC/what-i-wnna-do-after-a-baseline.gif">
</p>

Antes de entrenar un algoritmo, usted recuerda los apuntes de su magíster en ciencia de datos y recuerda que debe seguir una serie de *buenas prácticas* para entrenar correcta y debidamente su modelo. Después de un par de vueltas, llega a las siguientes tareas:

1. Separe los datos en conjuntos de train (70%), validation (20%) y test (10%). Fije una semilla para controlar la aleatoriedad. [0.5 puntos]
2. Implemente un `FunctionTransformer` para extraer el día, mes y año de la variable `date`. Guarde estas variables en el formato categorical de pandas. [1 punto]
3. Implemente un `ColumnTransformer` para procesar de manera adecuada los datos numéricos y categóricos. Use `OneHotEncoder` para las variables categóricas. `Nota:` Utilice el método `.set_output(transform='pandas')` para obtener un DataFrame como salida del `ColumnTransformer` [1 punto]
4. Guarde los pasos anteriores en un `Pipeline`, dejando como último paso el regresor `DummyRegressor` para generar predicciones en base a promedios. [0.5 punto]
5. Entrene el pipeline anterior y reporte la métrica `mean_absolute_error` sobre los datos de validación. ¿Cómo se interpreta esta métrica para el contexto del negocio? [0.5 puntos]
6. Finalmente, vuelva a entrenar el `Pipeline` pero esta vez usando `XGBRegressor` como modelo **utilizando los parámetros por default**. ¿Cómo cambia el MAE al implementar este algoritmo? ¿Es mejor o peor que el `DummyRegressor`? [1 punto]
7. Guarde ambos modelos en un archivo .pkl (uno cada uno) [0.5 puntos]

In [ ]:
from sklearn import set_config
set_config(transform_output="pandas")

#1. Separe los datos en conjuntos de train (70%), validation (20%) y test (10%). Fije una semilla para controlar la aleatoriedad.
from sklearn.model_selection import train_test_split

# Fijamos una semilla para la reproducibilidad
seed = 42

# Separacion inicial: 70% train, 30% temp
train_df, temp_df = train_test_split(df, test_size=0.3, random_state=seed)

# Separación de temp en validation (20%) y test (10%)
val_df, test_df = train_test_split(temp_df, test_size=0.33, random_state=seed)  # 33% de 30% es ~10%

# Verificación de tamaños
print(f"Tamaño de train: {len(train_df)}")
print(f"Tamaño de validation: {len(val_df)}")
print(f"Tamaño de test: {len(test_df)}")

Tamaño de train: 5219
Tamaño de validation: 1498
Tamaño de test: 739

In [ ]:
# Separar las variables predictoras (X) y la variable objetivo (y)
#Train
X_train = train_df.drop(columns=['quantity'])
y_train = train_df['quantity']
#Validacion
X_val = val_df.drop(columns=['quantity'])
y_val = val_df['quantity']
#Test
X_test = test_df.drop(columns=['quantity'])
y_test = test_df['quantity']

In [ ]:
#2. Implemente un FunctionTransformer para extraer el día, mes y año de la variable date.
# Guarde estas variables en el formato categorical de pandas.

from sklearn.preprocessing import FunctionTransformer

# Función que extrae día, mes y año especificando el formato de la fecha
def extract_date_components(df):
    # Especificamos el formato correcto de la columna 'date'
    date_format = '%d/%m/%y'  # El formato en el que parecen estar las fechas
    df['date'] = pd.to_datetime(df['date'], format=date_format, errors='coerce')  # 'errors="coerce"' para manejar fechas invalidas
    df['year'] = df['date'].dt.year.astype('category')
    df['month'] = df['date'].dt.month.astype('category')
    df['day'] = df['date'].dt.day.astype('category')
    return df.drop(columns=['date'])

# Creacion del FunctionTransformer
date_transformer = FunctionTransformer(extract_date_components)

# Aplicar el FunctionTransformer para extraer año, mes y día a X_train y X_val
X_train_transformed = date_transformer.transform(X_train.copy())
X_val_transformed = date_transformer.transform(X_val.copy())

# Verificamos las nuevas columnas
X_train_transformed.head()

,id,city,lat,long,pop,shop,brand,container,capacity,price,year,month,day
292,300,Patra,38.24444,21.73444,164250,shop_6,adult-cola,plastic,1.5lt,2.54,2012,4,30
3366,3416,Athens,37.97945,23.71622,667237,shop_1,gazoza,plastic,1.5lt,0.71,2015,2,28
3685,3741,Athens,37.96245,23.68708,667237,shop_3,adult-cola,can,330ml,0.66,2015,6,30
2404,2441,Athens,37.97945,23.71622,668203,shop_1,gazoza,can,330ml,0.30,2014,4,30
2855,2898,Irakleion,35.32787,25.14341,136202,shop_2,orange-power,can,330ml,0.56,2014,9,30

In [ ]:
#3. Implemente un ColumnTransformer para procesar de manera adecuada los datos numéricos y categóricos.
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Definir las columnas categóricas y numéricas
categorical_columns = ['year', 'month', 'day', 'city', 'shop', 'brand', 'container', 'capacity']
numerical_columns = ['lat', 'long', 'pop', 'price', 'quantity']

# Crear un Cclumntransformer para aplicar el escalado y onehotencoder
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),  # Escalar las variables numericas
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_columns)  # onehotencoder para las categiricas
    ],
    remainder='passthrough'  # Mantener cualquier otra columna sin transformar
)

# Configuramos la salida en formato DataFrame de pandas
from sklearn import set_config
set_config(transform_output="pandas")

In [ ]:
#4. Guarde los pasos anteriores en un Pipeline, dejando como último paso el regresor DummyRegressor para generar predicciones en base a promedios.
from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error

# Definir las columnas categóricas y numéricas
categorical_columns = ['year', 'month', 'day', 'city', 'shop', 'brand', 'container', 'capacity']
numerical_columns = ['lat', 'long', 'pop', 'price']

# Crear un ColumnTransformer para aplicar el escalado y OneHotEncoder sin salida esparsa
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),  # Escalar las variables numéricas
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_columns)  # OneHotEncoder sin salida esparsa
    ],
    remainder='passthrough'  # Mantener cualquier otra columna sin transformar
)

# Crear el pipeline con el preprocesador y el DummyRegressor
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', DummyRegressor(strategy='mean'))
])

#5.
# Entrenamos el pipeline con los datos ya transformados
pipeline.fit(X_train_transformed, y_train)

# Realizamos predicciones en el conjunto de validación
val_predictions = pipeline.predict(X_val_transformed)

# Calcular el MAE (Mean Absolute Error)
mae = mean_absolute_error(y_val, val_predictions)
print(f'MAE del DummyRegressor: {mae}')

MAE del DummyRegressor: 13308.134750658153

In [ ]:
#6.
from xgboost import XGBRegressor

# Pipeline con el preprocesador y el XGBRegressor
pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(random_state= seed))
])

# Entrenar el pipeline
pipeline_xgb.fit(X_train_transformed, y_train)

# Realizar predicciones
val_predictions_xgb = pipeline_xgb.predict(X_val_transformed)

# Calcular el MAE (Mean Absolute Error)
mae_xgb = mean_absolute_error(y_val, val_predictions_xgb)
print(f'MAE del XGBRegressor: {mae_xgb}')

MAE del XGBRegressor: 2402.1883264600197

In [ ]:
13308.134750658153/2402.1883264600197

5.540004754860191

El valor del MAE par Xgboost es alrededor de 5.5 veces menor que el DummyRegressor, por lo que claramente es un modelo muy superior.

In [ ]:
#7. Guarde ambos modelos en un archivo .pkl (uno cada uno)
import joblib

# Guardar el modelo DummyRegressor
joblib.dump(pipeline, 'dummy_regressor.pkl')

# Guardar el modelo XGBRegressor
joblib.dump(pipeline_xgb, 'xgb_regressor.pkl')

print("Modelos guardados correctamente.")

Modelos guardados correctamente.

## 2. Forzando relaciones entre parámetros con XGBoost (10 puntos)

<p align="center">
  <img src="https://64.media.tumblr.com/14cc45f9610a6ee341a45fd0d68f4dde/20d11b36022bca7b-bf/s640x960/67ab1db12ff73a530f649ac455c000945d99c0d6.gif">
</p>

Un colega aficionado a la economía le *sopla* que la demanda guarda una relación inversa con el precio del producto. Motivado para impresionar al querido corpóreo, se propone hacer uso de esta información para mejorar su modelo realizando las siguientes tareas:

1. Vuelva a entrenar el `Pipeline` con `XGBRegressor`, pero esta vez forzando una relación monótona negativa entre el precio y la cantidad. Para aplicar esta restricción apóyese en la siguiente <a href = https://xgboost.readthedocs.io/en/stable/tutorials/monotonic.html>documentación</a>. [6 puntos]

>Hint 1: Para implementar el constraint se le sugiere hacerlo especificando el nombre de la variable. De ser así, probablemente le sea útil **mantener el formato de pandas** antes del step de entrenamiento.

>Hint 2: Puede obtener el nombre de las columnas en el paso anterior al modelo regresor mediante el método `.get_feature_names_out()`

2. Luego, vuelva a reportar el `MAE` sobre el conjunto de validación. [1 puntos]

3. ¿Cómo cambia el error al incluir esta relación? ¿Tenía razón su amigo? [2 puntos]

4. Guarde su modelo en un archivo .pkl [1 punto]

In [ ]:
#1.
# Ajustamos el OneHotEncoder para mantener pandas y no usar matrices sparse com nos sugiere el hint 1
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_columns)
    ],
    remainder='passthrough'  # Mantener el formato pandas en las demas columnas
)

# Aplicar el FunctionTransformer para extraer año, mes y día
X_train_transformed = date_transformer.transform(X_train.copy())
Y_val_transformed = date_transformer.transform(X_val.copy())

# Ajustar el preprocesador para entrenar y obtener los nombres de las columnas
preprocessor.fit(X_train_transformed)
feature_names = preprocessor.get_feature_names_out()

# Verificar como se llama la columna 'price' despues del preprocesamiento
price_feature_name = [name for name in feature_names if 'price' in name][0]
print(f'Nombre de la columna "price" después del preprocesamiento: {price_feature_name}')

# Crear el pipeline con la restricción monótona aplicada a la columna procesada
pipeline_xgb_monotonic = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(random_state=seed, monotone_constraints={price_feature_name: -1}))
])

# Entrenar el pipeline con los datos transformados en formato pandas
pipeline_xgb_monotonic.fit(X_train_transformed, y_train)

#2.
# Realizar predicciones en el conjunto de validación
val_predictions_xgb_monotonic = pipeline_xgb_monotonic.predict(X_val_transformed)

# Calcular el MAE (Mean Absolute Error)
mae_xgb_monotonic = mean_absolute_error(y_val, val_predictions_xgb_monotonic)
print(f'MAE del XGBRegressor con restricciones monótonas (nombre ajustado): {mae_xgb_monotonic}')

Nombre de la columna "price" después del preprocesamiento: num__price
MAE del XGBRegressor con restricciones monótonas (nombre ajustado): 2493.6477391404687

3. El MAE reportado aumento ligeramente de 2402.18 a 2493.65, lo que sugiere que la restricción monotona negativa no mejora el modelo en este caso.

  Por lo tanto, la relacion monotona negativa no parece beneficiar al modelo. Es posible que la relacion entre precio y cantidad sea mas compleja de lo que el colega habia anticipado, y limitarla a ser monotona negativa podria estar impidiendo que el modelo capture correctamente todos los patrones.

In [ ]:
#4.
# Guardar el modelo XGBRegressor
joblib.dump(pipeline_xgb_monotonic, 'xgb_monotonic.pkl')

print("Modelos guardados correctamente.")

Modelos guardados correctamente.

## 3 Optimización de Hiperparámetros con Optuna (20 puntos)

<p align="center">
  <img src="https://media.tenor.com/fmNdyGN4z5kAAAAi/hacking-lucy.gif">
</p>

Luego de presentarle sus resultados, Fiu le pregunta si es posible mejorar *aun más* su modelo. En particular, le comenta de la optimización de hiperparámetros con metodologías bayesianas a través del paquete `optuna`. Como usted es un aficionado al entrenamiento de modelos de ML, se propone implementar la descabellada idea de su jefe.

A partir de la mejor configuración obtenida en la sección anterior, utilice `optuna` para optimizar sus hiperparámetros. En particular, se pide que su optimización considere lo siguiente:

- Fijar una semilla en las instancias necesarias para garantizar la reproducibilidad de resultados
- Utilice `TPESampler` como método de muestreo
- De `XGBRegressor`, optimice los siguientes hiperparámetros:
    - `learning_rate` buscando valores flotantes en el rango (0.001, 0.1)
    - `n_estimators` buscando valores enteros en el rango (50, 1000)
    - `max_depth` buscando valores enteros en el rango (3, 10)
    - `max_leaves` buscando valores enteros en el rango (0, 100)
    - `min_child_weight` buscando valores enteros en el rango (1, 5)
    - `reg_alpha` buscando valores flotantes en el rango (0, 1)
    - `reg_lambda` buscando valores flotantes en el rango (0, 1)
- De `OneHotEncoder`, optimice el hiperparámetro `min_frequency` buscando el mejor valor flotante en el rango (0.0, 1.0)

Para ello se pide los siguientes pasos:
1. Implemente una función `objective()` que permita minimizar el `MAE` en el conjunto de validación. Use el método `.set_user_attr()` para almacenar el mejor pipeline entrenado. [10 puntos]
2. Fije el tiempo de entrenamiento a 5 minutos. [1 punto]
3. Optimizar el modelo y reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
4. Explique cada hiperparámetro y su rol en el modelo. ¿Hacen sentido los rangos de optimización indicados? [5 puntos]
5. Guardar su modelo en un archivo .pkl [1 punto]

In [ ]:
#!pip install optuna

In [ ]:
import optuna
from optuna.samplers import TPESampler
# Inserte su código acá
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error

#1.
def objective(trial):
    # Hiperparametros de XGBRegressor
    learning_rate = trial.suggest_float('learning_rate', 0.001, 0.1)
    n_estimators = trial.suggest_int('n_estimators', 50, 1000)
    max_depth = trial.suggest_int('max_depth', 3, 10)
    max_leaves = trial.suggest_int('max_leaves', 0, 100)
    min_child_weight = trial.suggest_int('min_child_weight', 1, 5)
    reg_alpha = trial.suggest_float('reg_alpha', 0.0, 1.0)
    reg_lambda = trial.suggest_float('reg_lambda', 0.0, 1.0)

    # Hiperparametro del OneHotEncoder
    min_frequency = trial.suggest_float('min_frequency', 0.0, 1.0)

    # Ajustamos el OneHotEncoder con el min_frequency sugerido
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numerical_columns),
            ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False, min_frequency=min_frequency), categorical_columns)
        ],
        remainder='passthrough'
    )

    # Crear el pipeline
    pipeline_xgb_optuna = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('regressor', XGBRegressor(
            random_state=seed,
            learning_rate=learning_rate,
            n_estimators=n_estimators,
            max_depth=max_depth,
            max_leaves=max_leaves,
            min_child_weight=min_child_weight,
            reg_alpha=reg_alpha,
            reg_lambda=reg_lambda
        ))
    ])

    # Entrenar el pipeline con los datos transformados
    pipeline_xgb_optuna.fit(X_train_transformed, y_train)

    # Realizar predicciones en el conjunto de validación
    val_predictions_optuna = pipeline_xgb_optuna.predict(X_val_transformed)

    # Calcular el MAE
    mae = mean_absolute_error(y_val, val_predictions_optuna)

    # Almacenar el mejor pipeline en el trial utilizando set_user_attr
    trial.set_user_attr("best_pipeline", pipeline_xgb_optuna)

    return mae

In [ ]:
#2.
# Configurar el sampler de Optuna
sampler = TPESampler(seed=seed)

# Crear el estudio de Optuna
study = optuna.create_study(direction='minimize', sampler=sampler)

# Ejecutar la optimizacion durante 5 minutos (300 segundos)
study.optimize(objective, timeout=300)

# Imprimir los mejores hiperparametros encontrados
print(f'Mejor MAE: {study.best_value}')
print(f'Mejores hiperparámetros: {study.best_params}')

[I 2024-10-24 23:40:26,974] A new study created in memory with name: no-name-38f3d127-de9d-4713-80d3-ce09f69bb0c2
[I 2024-10-24 23:40:28,554] Trial 0 finished with value: 6988.087557824495 and parameters: {'learning_rate': 0.03807947176588889, 'n_estimators': 954, 'max_depth': 8, 'max_leaves': 60, 'min_child_weight': 1, 'reg_alpha': 0.15599452033620265, 'reg_lambda': 0.05808361216819946, 'min_frequency': 0.8661761457749352}. Best is trial 0 with value: 6988.087557824495.
[I 2024-10-24 23:40:29,169] Trial 1 finished with value: 3492.0901505555585 and parameters: {'learning_rate': 0.06051038616257767, 'n_estimators': 723, 'max_depth': 3, 'max_leaves': 97, 'min_child_weight': 5, 'reg_alpha': 0.21233911067827616, 'reg_lambda': 0.18182496720710062, 'min_frequency': 0.18340450985343382}. Best is trial 1 with value: 3492.0901505555585.
[I 2024-10-24 23:40:29,831] Trial 2 finished with value: 6636.115521134298 and parameters: {'learning_rate': 0.03111998205299424, 'n_estimators': 549, 'max_depth': 6, 'max_leaves': 29, 'min_child_weight': 4, 'reg_alpha': 0.13949386065204183, 'reg_lambda': 0.29214464853521815, 'min_frequency': 0.3663618432936917}. Best is trial 1 with value: 3492.0901505555585.
[I 2024-10-24 23:40:30,659] Trial 3 finished with value: 3075.209984650758 and parameters: {'learning_rate': 0.04615092843748656, 'n_estimators': 796, 'max_depth': 4, 'max_leaves': 51, 'min_child_weight': 3, 'reg_alpha': 0.046450412719997725, 'reg_lambda': 0.6075448519014384, 'min_frequency': 0.17052412368729153}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:32,573] Trial 4 finished with value: 6820.438619819916 and parameters: {'learning_rate': 0.0074401077055426725, 'n_estimators': 952, 'max_depth': 10, 'max_leaves': 81, 'min_child_weight': 2, 'reg_alpha': 0.09767211400638387, 'reg_lambda': 0.6842330265121569, 'min_frequency': 0.4401524937396013}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:32,986] Trial 5 finished with value: 7471.752660448306 and parameters: {'learning_rate': 0.013081785249633104, 'n_estimators': 520, 'max_depth': 3, 'max_leaves': 91, 'min_child_weight': 2, 'reg_alpha': 0.662522284353982, 'reg_lambda': 0.31171107608941095, 'min_frequency': 0.5200680211778108}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:34,347] Trial 6 finished with value: 6861.278046346953 and parameters: {'learning_rate': 0.05512431765498469, 'n_estimators': 225, 'max_depth': 10, 'max_leaves': 78, 'min_child_weight': 5, 'reg_alpha': 0.8948273504276488, 'reg_lambda': 0.5978999788110851, 'min_frequency': 0.9218742350231168}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:36,309] Trial 7 finished with value: 8707.646509799524 and parameters: {'learning_rate': 0.00976075770314003, 'n_estimators': 236, 'max_depth': 3, 'max_leaves': 32, 'min_child_weight': 2, 'reg_alpha': 0.2713490317738959, 'reg_lambda': 0.8287375091519293, 'min_frequency': 0.3567533266935893}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:37,624] Trial 8 finished with value: 3966.76558710768 and parameters: {'learning_rate': 0.028812516459050697, 'n_estimators': 566, 'max_depth': 4, 'max_leaves': 81, 'min_child_weight': 1, 'reg_alpha': 0.9868869366005173, 'reg_lambda': 0.7722447692966574, 'min_frequency': 0.1987156815341724}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:39,930] Trial 9 finished with value: 7346.796441479264 and parameters: {'learning_rate': 0.0015466895952366377, 'n_estimators': 825, 'max_depth': 8, 'max_leaves': 73, 'min_child_weight': 4, 'reg_alpha': 0.07404465173409036, 'reg_lambda': 0.3584657285442726, 'min_frequency': 0.11586905952512971}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:40,167] Trial 10 finished with value: 13308.134690003339 and parameters: {'learning_rate': 0.0922925348311468, 'n_estimators': 55, 'max_depth': 5, 'max_leaves': 1, 'min_child_weight': 3, 'reg_alpha': 0.426812895383314, 'reg_lambda': 0.9597707459454197, 'min_frequency': 0.011852595611645367}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:40,963] Trial 11 finished with value: 6751.158247373451 and parameters: {'learning_rate': 0.06569237816113468, 'n_estimators': 731, 'max_depth': 5, 'max_leaves': 44, 'min_child_weight': 5, 'reg_alpha': 0.3587862975096967, 'reg_lambda': 0.06782026776262084, 'min_frequency': 0.635517147692292}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:41,544] Trial 12 finished with value: 4663.792685128023 and parameters: {'learning_rate': 0.07143256650213327, 'n_estimators': 714, 'max_depth': 3, 'max_leaves': 6, 'min_child_weight': 4, 'reg_alpha': 0.0077576833321514466, 'reg_lambda': 0.4687052188878421, 'min_frequency': 0.23968278799454548}. Best is trial 3 with value: 3075.209984650758.
[I 2024-10-24 23:40:42,857] Trial 13 finished with value: 2227.5827390622394 and parameters: {'learning_rate': 0.07742047722562705, 'n_estimators': 753, 'max_depth': 5, 'max_leaves': 100, 'min_child_weight': 3, 'reg_alpha': 0.6608557252922866, 'reg_lambda': 0.4984881742637889, 'min_frequency': 0.004470039476462462}. Best is trial 13 with value: 2227.5827390622394.
[I 2024-10-24 23:40:44,244] Trial 14 finished with value: 2222.1122647579587 and parameters: {'learning_rate': 0.08166358818148486, 'n_estimators': 829, 'max_depth': 5, 'max_leaves': 61, 'min_child_weight': 3, 'reg_alpha': 0.7267506372103785, 'reg_lambda': 0.4621147584011279, 'min_frequency': 0.0016620296848777168}. Best is trial 14 with value: 2222.1122647579587.
[I 2024-10-24 23:40:45,939] Trial 15 finished with value: 2105.4345303829587 and parameters: {'learning_rate': 0.08344481504923282, 'n_estimators': 620, 'max_depth': 7, 'max_leaves': 63, 'min_child_weight': 3, 'reg_alpha': 0.6590286048089737, 'reg_lambda': 0.4801104778560333, 'min_frequency': 0.0024139548110165324}. Best is trial 15 with value: 2105.4345303829587.
[I 2024-10-24 23:40:46,640] Trial 16 finished with value: 7029.736519134888 and parameters: {'learning_rate': 0.09449091931362905, 'n_estimators': 388, 'max_depth': 7, 'max_leaves': 61, 'min_child_weight': 2, 'reg_alpha': 0.6308314706796185, 'reg_lambda': 0.4149255685244614, 'min_frequency': 0.6394684662708778}. Best is trial 15 with value: 2105.4345303829587.
[I 2024-10-24 23:40:51,581] Trial 17 finished with value: 2093.0368135704375 and parameters: {'learning_rate': 0.08411438767879004, 'n_estimators': 616, 'max_depth': 7, 'max_leaves': 65, 'min_child_weight': 4, 'reg_alpha': 0.8041831949427771, 'reg_lambda': 0.5824205249122129, 'min_frequency': 0.004759505808393071}. Best is trial 17 with value: 2093.0368135704375.
[I 2024-10-24 23:40:52,342] Trial 18 finished with value: 4678.248961139267 and parameters: {'learning_rate': 0.08507170657364552, 'n_estimators': 453, 'max_depth': 8, 'max_leaves': 38, 'min_child_weight': 4, 'reg_alpha': 0.8120700012360597, 'reg_lambda': 0.5736894675055919, 'min_frequency': 0.29293951492252984}. Best is trial 17 with value: 2093.0368135704375.
[I 2024-10-24 23:40:53,715] Trial 19 finished with value: 3063.667939658477 and parameters: {'learning_rate': 0.09984468836282745, 'n_estimators': 642, 'max_depth': 7, 'max_leaves': 69, 'min_child_weight': 4, 'reg_alpha': 0.5014570154223668, 'reg_lambda': 0.7255429663622144, 'min_frequency': 0.09017405294742764}. Best is trial 17 with value: 2093.0368135704375.
[I 2024-10-24 23:40:54,183] Trial 20 finished with value: 6621.235390595664 and parameters: {'learning_rate': 0.0715448995770748, 'n_estimators': 339, 'max_depth': 9, 'max_leaves': 18, 'min_child_weight': 3, 'reg_alpha': 0.5065803901639296, 'reg_lambda': 0.9217073500188905, 'min_frequency': 0.7305414525438465}. Best is trial 17 with value: 2093.0368135704375.
[I 2024-10-24 23:40:55,879] Trial 21 finished with value: 2091.9830897576976 and parameters: {'learning_rate': 0.08218065461343792, 'n_estimators': 875, 'max_depth': 6, 'max_leaves': 56, 'min_child_weight': 3, 'reg_alpha': 0.7882937674472151, 'reg_lambda': 0.21781112379201067, 'min_frequency': 0.06934727309538366}. Best is trial 21 with value: 2091.9830897576976.
[I 2024-10-24 23:40:57,066] Trial 22 finished with value: 2942.900556780786 and parameters: {'learning_rate': 0.0867419753612744, 'n_estimators': 633, 'max_depth': 6, 'max_leaves': 52, 'min_child_weight': 3, 'reg_alpha': 0.7990587255912357, 'reg_lambda': 0.20654125522770256, 'min_frequency': 0.11939785154402875}. Best is trial 21 with value: 2091.9830897576976.
[I 2024-10-24 23:40:59,194] Trial 23 finished with value: 2105.169958056054 and parameters: {'learning_rate': 0.0761338602004732, 'n_estimators': 894, 'max_depth': 7, 'max_leaves': 56, 'min_child_weight': 4, 'reg_alpha': 0.5741406720239703, 'reg_lambda': 0.16826213365689052, 'min_frequency': 0.07484545115078033}. Best is trial 21 with value: 2091.9830897576976.
[I 2024-10-24 23:41:00,471] Trial 24 finished with value: 4882.640556801463 and parameters: {'learning_rate': 0.07225238681930962, 'n_estimators': 895, 'max_depth': 6, 'max_leaves': 44, 'min_child_weight': 4, 'reg_alpha': 0.5699054756297403, 'reg_lambda': 0.16557137801140304, 'min_frequency': 0.2786923751108903}. Best is trial 21 with value: 2091.9830897576976.
[I 2024-10-24 23:41:05,853] Trial 25 finished with value: 2338.42659695349 and parameters: {'learning_rate': 0.06362734716483213, 'n_estimators': 886, 'max_depth': 9, 'max_leaves': 53, 'min_child_weight': 5, 'reg_alpha': 0.8678494840189113, 'reg_lambda': 0.02287437210526344, 'min_frequency': 0.0826410841529217}. Best is trial 21 with value: 2091.9830897576976.
[I 2024-10-24 23:41:08,196] Trial 26 finished with value: 2073.339030491176 and parameters: {'learning_rate': 0.0521258480588154, 'n_estimators': 995, 'max_depth': 7, 'max_leaves': 69, 'min_child_weight': 4, 'reg_alpha': 0.9916294029778024, 'reg_lambda': 0.2349127426674303, 'min_frequency': 0.07557873522280331}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:09,590] Trial 27 finished with value: 4783.160297785964 and parameters: {'learning_rate': 0.049136907099616864, 'n_estimators': 985, 'max_depth': 6, 'max_leaves': 69, 'min_child_weight': 4, 'reg_alpha': 0.9900537216466941, 'reg_lambda': 0.2825137975289681, 'min_frequency': 0.3326446984064106}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:11,247] Trial 28 finished with value: 7282.308928017304 and parameters: {'learning_rate': 0.04159822110563623, 'n_estimators': 893, 'max_depth': 8, 'max_leaves': 86, 'min_child_weight': 5, 'reg_alpha': 0.8902852704930355, 'reg_lambda': 0.24931878014624048, 'min_frequency': 0.43292906250243435}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:13,604] Trial 29 finished with value: 2957.7119970181598 and parameters: {'learning_rate': 0.02309497480663167, 'n_estimators': 979, 'max_depth': 7, 'max_leaves': 65, 'min_child_weight': 1, 'reg_alpha': 0.7629778660981089, 'reg_lambda': 0.12025248304880905, 'min_frequency': 0.15685387585125854}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:18,367] Trial 30 finished with value: 4793.0701523845755 and parameters: {'learning_rate': 0.05538644573364352, 'n_estimators': 931, 'max_depth': 9, 'max_leaves': 42, 'min_child_weight': 4, 'reg_alpha': 0.9272191689294649, 'reg_lambda': 0.4025131842274328, 'min_frequency': 0.23958030241219697}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:20,443] Trial 31 finished with value: 2101.6603650244597 and parameters: {'learning_rate': 0.07719307674683765, 'n_estimators': 855, 'max_depth': 7, 'max_leaves': 74, 'min_child_weight': 4, 'reg_alpha': 0.7282783911295084, 'reg_lambda': 0.10301538610840852, 'min_frequency': 0.06060519162367231}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:22,008] Trial 32 finished with value: 2111.005761914323 and parameters: {'learning_rate': 0.09142865896632067, 'n_estimators': 822, 'max_depth': 6, 'max_leaves': 76, 'min_child_weight': 5, 'reg_alpha': 0.7297176777662329, 'reg_lambda': 0.09192387916475722, 'min_frequency': 0.07309645999013878}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:24,677] Trial 33 finished with value: 3057.2964825496497 and parameters: {'learning_rate': 0.05756575204532724, 'n_estimators': 681, 'max_depth': 8, 'max_leaves': 87, 'min_child_weight': 4, 'reg_alpha': 0.8476701276113353, 'reg_lambda': 0.21586830034352034, 'min_frequency': 0.16391558324937583}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:27,219] Trial 34 finished with value: 2101.2041921781124 and parameters: {'learning_rate': 0.07837510090170943, 'n_estimators': 853, 'max_depth': 7, 'max_leaves': 70, 'min_child_weight': 3, 'reg_alpha': 0.9527102811372877, 'reg_lambda': 0.012108611751461218, 'min_frequency': 0.0595671917326316}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:28,707] Trial 35 finished with value: 4870.801214770736 and parameters: {'learning_rate': 0.06650544561142276, 'n_estimators': 792, 'max_depth': 6, 'max_leaves': 58, 'min_child_weight': 3, 'reg_alpha': 0.9453403664258808, 'reg_lambda': 0.007980416901871564, 'min_frequency': 0.23131134034854528}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:33,816] Trial 36 finished with value: 3058.075560138127 and parameters: {'learning_rate': 0.09890973099991952, 'n_estimators': 996, 'max_depth': 7, 'max_leaves': 68, 'min_child_weight': 2, 'reg_alpha': 0.9601809441984369, 'reg_lambda': 0.3577137087739164, 'min_frequency': 0.13860805884232377}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:35,436] Trial 37 finished with value: 2193.306443258981 and parameters: {'learning_rate': 0.03742842513798439, 'n_estimators': 761, 'max_depth': 6, 'max_leaves': 49, 'min_child_weight': 3, 'reg_alpha': 0.840170133587494, 'reg_lambda': 0.6619221451372976, 'min_frequency': 0.04945241492204298}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:37,497] Trial 38 finished with value: 3083.783739810633 and parameters: {'learning_rate': 0.08883686722915715, 'n_estimators': 924, 'max_depth': 8, 'max_leaves': 86, 'min_child_weight': 2, 'reg_alpha': 0.919068106234162, 'reg_lambda': 0.5576267343225451, 'min_frequency': 0.1966535147398764}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:38,085] Trial 39 finished with value: 6660.666154257923 and parameters: {'learning_rate': 0.08011687020902206, 'n_estimators': 563, 'max_depth': 4, 'max_leaves': 93, 'min_child_weight': 3, 'reg_alpha': 0.7863575958695415, 'reg_lambda': 0.14156373882984097, 'min_frequency': 0.4700918093036224}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:39,147] Trial 40 finished with value: 7155.479805186212 and parameters: {'learning_rate': 0.06067821248003673, 'n_estimators': 508, 'max_depth': 9, 'max_leaves': 81, 'min_child_weight': 3, 'reg_alpha': 0.998185890437063, 'reg_lambda': 0.320744258729213, 'min_frequency': 0.8822786087397013}. Best is trial 26 with value: 2073.339030491176.
[I 2024-10-24 23:41:41,161] Trial 41 finished with value: 2071.1148999447178 and parameters: {'learning_rate': 0.0761130054918327, 'n_estimators': 840, 'max_depth': 7, 'max_leaves': 73, 'min_child_weight': 4, 'reg_alpha': 0.73821383200996, 'reg_lambda': 0.07502587031640018, 'min_frequency': 0.05265378441886888}. Best is trial 41 with value: 2071.1148999447178.
[I 2024-10-24 23:41:46,243] Trial 42 finished with value: 2983.8269804074703 and parameters: {'learning_rate': 0.06893096606705187, 'n_estimators': 784, 'max_depth': 7, 'max_leaves': 69, 'min_child_weight': 4, 'reg_alpha': 0.8881197309514359, 'reg_lambda': 0.03872121784271558, 'min_frequency': 0.1289549374625074}. Best is trial 41 with value: 2071.1148999447178.
[I 2024-10-24 23:41:48,147] Trial 43 finished with value: 3027.1951822808014 and parameters: {'learning_rate': 0.07581338003436609, 'n_estimators': 942, 'max_depth': 8, 'max_leaves': 73, 'min_child_weight': 4, 'reg_alpha': 0.8349789595583478, 'reg_lambda': 0.07532165423571488, 'min_frequency': 0.1848987975553109}. Best is trial 41 with value: 2071.1148999447178.
[I 2024-10-24 23:41:50,014] Trial 44 finished with value: 2253.849454872121 and parameters: {'learning_rate': 0.018581994435440105, 'n_estimators': 861, 'max_depth': 6, 'max_leaves': 79, 'min_child_weight': 5, 'reg_alpha': 0.7475883447823983, 'reg_lambda': 0.25205562785583085, 'min_frequency': 0.0631717020047243}. Best is trial 41 with value: 2071.1148999447178.
[I 2024-10-24 23:41:51,056] Trial 45 finished with value: 6877.4365658931965 and parameters: {'learning_rate': 0.0506750955443097, 'n_estimators': 952, 'max_depth': 5, 'max_leaves': 56, 'min_child_weight': 2, 'reg_alpha': 0.9433795149855579, 'reg_lambda': 0.04929901977768462, 'min_frequency': 0.9716452764893935}. Best is trial 41 with value: 2071.1148999447178.
[I 2024-10-24 23:41:53,101] Trial 46 finished with value: 2098.7990989939713 and parameters: {'learning_rate': 0.09391542572730525, 'n_estimators': 839, 'max_depth': 7, 'max_leaves': 65, 'min_child_weight': 3, 'reg_alpha': 0.2393944929245374, 'reg_lambda': 0.6589724576478847, 'min_frequency': 0.03655095455950798}. Best is trial 41 with value: 2071.1148999447178.
[I 2024-10-24 23:41:54,509] Trial 47 finished with value: 2070.3402541278997 and parameters: {'learning_rate': 0.09493066848470758, 'n_estimators': 697, 'max_depth': 6, 'max_leaves': 64, 'min_child_weight': 4, 'reg_alpha': 0.2176871763280036, 'reg_lambda': 0.6560431499615388, 'min_frequency': 0.03693149329260196}. Best is trial 47 with value: 2070.3402541278997.
[I 2024-10-24 23:41:55,555] Trial 48 finished with value: 2913.557758815139 and parameters: {'learning_rate': 0.08839019792743949, 'n_estimators': 703, 'max_depth': 5, 'max_leaves': 47, 'min_child_weight': 4, 'reg_alpha': 0.3398585916054179, 'reg_lambda': 0.7978008312656066, 'min_frequency': 0.11222844558616682}. Best is trial 47 with value: 2070.3402541278997.
[I 2024-10-24 23:41:59,827] Trial 49 finished with value: 6814.250122396268 and parameters: {'learning_rate': 0.03292017827818684, 'n_estimators': 672, 'max_depth': 6, 'max_leaves': 59, 'min_child_weight': 5, 'reg_alpha': 0.16342952420781776, 'reg_lambda': 0.544177438488237, 'min_frequency': 0.5616787381338312}. Best is trial 47 with value: 2070.3402541278997.
[I 2024-10-24 23:42:00,421] Trial 50 finished with value: 6715.6353520392095 and parameters: {'learning_rate': 0.09637457498691207, 'n_estimators': 608, 'max_depth': 4, 'max_leaves': 37, 'min_child_weight': 4, 'reg_alpha': 0.6060201281914843, 'reg_lambda': 0.7120641992251739, 'min_frequency': 0.4055498511482143}. Best is trial 47 with value: 2070.3402541278997.
[I 2024-10-24 23:42:02,316] Trial 51 finished with value: 2124.7540328836885 and parameters: {'learning_rate': 0.09264669439460746, 'n_estimators': 754, 'max_depth': 7, 'max_leaves': 63, 'min_child_weight': 3, 'reg_alpha': 0.2611145136535754, 'reg_lambda': 0.6350186504969845, 'min_frequency': 0.031137153996922233}. Best is trial 47 with value: 2070.3402541278997.
[I 2024-10-24 23:42:04,385] Trial 52 finished with value: 2096.6823611495015 and parameters: {'learning_rate': 0.08676706068732715, 'n_estimators': 815, 'max_depth': 8, 'max_leaves': 64, 'min_child_weight': 4, 'reg_alpha': 0.21881189103661625, 'reg_lambda': 0.6296617792167034, 'min_frequency': 0.0229298276790397}. Best is trial 47 with value: 2070.3402541278997.
[I 2024-10-24 23:42:06,255] Trial 53 finished with value: 2097.3912801704355 and parameters: {'learning_rate': 0.0838579715210382, 'n_estimators': 727, 'max_depth': 8, 'max_leaves': 66, 'min_child_weight': 4, 'reg_alpha': 0.1669404331976317, 'reg_lambda': 0.6111613127945708, 'min_frequency': 0.001989981767782062}. Best is trial 47 with value: 2070.3402541278997.

Mejor MAE: 2021.2459897702145
Mejores hiperparámetros: {'learning_rate': 0.05258525231231221, 'n_estimators': 678, 'max_depth': 10, 'max_leaves': 79, 'min_child_weight': 4, 'reg_alpha': 0.5332902675779876, 'reg_lambda': 0.3305773756436482, 'min_frequency': 0.029251484155416785}

In [ ]:
#3.
# Reportar los resultados de la optimización
print(f'Número de trials: {len(study.trials)}')
print(f'Mejor MAE obtenido: {study.best_value}')
print(f'Mejores hiperparámetros: {study.best_params}')

# Acceder al mejor pipeline
best_trial = study.best_trial
best_pipeline = best_trial.user_attrs["best_pipeline"]

Número de trials: 133
Mejor MAE obtenido: 2021.2459897702145
Mejores hiperparámetros: {'learning_rate': 0.05258525231231221, 'n_estimators': 678, 'max_depth': 10, 'max_leaves': 79, 'min_child_weight': 4, 'reg_alpha': 0.5332902675779876, 'reg_lambda': 0.3305773756436482, 'min_frequency': 0.029251484155416785}

3. Vemos que el MAE ha disminuido considerablemente desde los experimentos anteriores:

* Sin restricciones: 2402.18
* Con restricciones monótonas: 2493.64
* Con Optuna: 2039.46

El nuevo MAE es 362.72 puntos mas bajo que el mejor modelo anterior, lo que indica una mejora significativa en la capacidad predictiva del modelo.

El cambio se debe a la optimización de hiperparametros con Optuna, que ha permitido encontrar una configuración mas adecuada de hiperparametros para el modelo XGBRegressor y el preprocesador OHE, esto lo hizo explorado un amplio espacio de hiperparametros, encontrando la mejor combinacion posible para este conjunto de datos.

Ademas Optuna usa un enfoque bayesiano para optimizar, lo que significa que cada prueba aprovecha la información de los intentos anteriores. Esto lo hace más eficiente que una simple búsqueda aleatoria o en cuadricula como lo es GridSearchCV de scikit-learn.

4.  Explique cada hiperparámetro y su rol en el modelo. ¿Hacen sentido los rangos de optimización indicados?

* Leaning rate:

El learning rate controla la tasa de aprendizaje del modelo, es decir, que tanto se ajustan los pesos de los arboles en cada iteracion. Valores más bajos permiten que el modelo aprenda mas lentamente pero con mayor precision. Un valor bajo de learning_rate hace que el modelo sea más robusto pero mas lento para entrenar, mientras que un valor alto podria hacer que el modelo aprenda patrones demasiado raido, lo que puede llevar a sobreajuste.

El rango 0.001 a 0.1 es comunmente utilizado para optimizar la tasa de aprendizaje en XGBoost. El valor default de este es de 0.36.

---

* n_estimators:

Indica el numero de arboles a construir en el ensamble de XGBoost. Mas arboles generalmente ayudan al modelo a aprender mejor, pero tambien aumentan el tiempo de entrenamiento y el riesgo de sobreajuste si el numero es muy alto. Por tanto, un mayor numero de estimadores puede mejorar el rendimiento, pero hay un punto en el que añadir mas arboles ya no aporta mejora significativa.

El rango 50 - 1000 es razonable. Menos de 50 qrboles puede ser insuficiente para capturar patrones complejos, mientras que mas de 1000 puede aumentar el riesgo de sobreajuste y el costo computacional sin mejorar mucho el rendimiento.

---
* max_depth:

Define la profundidad maxima que puede tener cada arbol. Los arboles mass profundos son mas capaces de capturar relaciones complejas en los datos, pero tambien son mas propensos a sobreajustar. Por lo tanto, este parametro controla la complejidad del modelo.

El rango de 3 a 10 es adecuado cosidrando que el default es de 6. Es comun comenzar con un valor pequeño, como max_depth = 3 y aumentarlo hasta que el rendimiento en el conjunto de validación deje de mejorar.

---

* max_leaves:

Este parametro limita el numero máximo de hojas en cada arbol. Recordemos que las hojas representan nodos terminales que definen las reglas de predicción del arbol. Asi, este hiperparametro actua como una forma de regular la complejidad de los arboles. Un numero menor de hojas puede simplificar los arboles, mientras que un numero mayor permite arboles mas complejos y detallados.

El rango de 0 a 100 es razonable. Un valor de 0 indica que no se impone ninguna restricción, lo que puede resultar en un consumo elevado de memoria durante el entrenamiento.

---

* min_child_weight:

Se encarga de especificar el peso mínimo de las instancias que deben estar presentes en un nodo hijo para que se permita la división. Este valor actúa como un regularizador ya que evita que el modelo divida un nodo si no hay suficientes datos en una rama, lo que ayuda a reducir el sobreajuste.

El rango de 1 a 5 es parece ser comun. Los valores mas bajos permiten mas divisiones, lo que puede ser util para modelos mas complejos, mientras que valores mas altos evitan divisiones excesivas.

---

* reg_alpha:

Controla la regularización L1 (Lasso) que penaliza los pesos del modelo. Ayuda a reducir el sobreajuste forzando a que algunos pesos sean 0.

El rango de 0 a 1 es comun. Un valor de 0 significa que no hay regularización, mientras que valores más altos aplican mayor penalización.

---

* reg_lambda:

Controla la regularización L2 (Ridge), que penaliza los pesos grandes del modelo. Tambien reduce el sobreajuste, pero lo hace suavizando los pesos en lugar de eliminarlos.

Igaulemnte, el el rango de 0 a 1 es adecuado. Un valor de 0 significa que no hay regularizacion, mientras que un valor cercano a 1 aplica una regularizacion mas fuerte.

---

* min_frequency:

Este hiperparametro controla el umbral minimo de frecuencia para incluir categorias en la codificación One-Hot. Si una categoria aparece con una frecuencia menor al valor indicado, se agrupa en una categoría "otros". Por tanto, este hiperparametro reduce la dimensionalidad del modelo, agrupando categorías raras en una unica categoría, lo que puede mejorar la capacidad de generalización del modelo.

Un rango de 0 a 1 es logico. Un valor cercano a 0  incluye más categorías (todas para exactamente 0), mientras que un valor cercano a 1 agrupa más categorías raras.

---

Referencias:

* https://xgboost.readthedocs.io/en/stable/parameter.html
* https://medium.com/@rithpansanga/the-main-parameters-in-xgboost-and-their-effects-on-model-performance-4f9833cac7c

In [ ]:
#5.
import joblib

# Guardar el mejor pipeline
joblib.dump(best_pipeline, 'xgb_regressor_optuna_best_pipeline.pkl')

print("Mejor pipeline guardado correctamente.")

Mejor pipeline guardado correctamente.

## 4. Optimización de Hiperparámetros con Optuna y Prunners (17 puntos)

<p align="center">
  <img src="https://i.pinimg.com/originals/90/16/f9/9016f919c2259f3d0e8fe465049638a7.gif">
</p>

Después de optimizar el rendimiento de su modelo varias veces, Fiu le pregunta si no es posible optimizar el entrenamiento del modelo en sí mismo. Después de leer un par de post de personas de dudosa reputación en la *deepweb*, usted llega a la conclusión que puede cumplir este objetivo mediante la implementación de **Prunning**.

Vuelva a optimizar los mismos hiperparámetros que la sección pasada, pero esta vez utilizando **Prunning** en la optimización. En particular, usted debe:

1. Responder: ¿Qué es prunning? ¿De qué forma debería impactar en el entrenamiento? [2 puntos]
2. Redefinir la función `objective()` utilizando `optuna.integration.XGBoostPruningCallback` como método de **Prunning** [10 puntos]
3. Fijar nuevamente el tiempo de entrenamiento a 5 minutos [1 punto]
4. Reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
5. Guardar su modelo en un archivo .pkl [1 punto]

Nota: Si quieren silenciar los prints obtenidos en el prunning, pueden hacerlo mediante el siguiente comando:

```
optuna.logging.set_verbosity(optuna.logging.WARNING)
```

De implementar la opción anterior, pueden especificar `show_progress_bar = True` en el método `optimize` para *más sabor*.

Hint: Si quieren especificar parámetros del método .fit() del modelo a través del pipeline, pueden hacerlo por medio de la siguiente sintaxis: `pipeline.fit(stepmodelo__parametro = valor)`

Hint2: Este <a href = https://stackoverflow.com/questions/40329576/sklearn-pass-fit-parameters-to-xgboost-in-pipeline>enlace</a> les puede ser de ayuda en su implementación

In [ ]:
!pip install optuna-integration[xgboost]

**¿Qué es prunning? ¿De qué forma debería impactar en el entrenamiento?**
Prunning es una técnica que se utiliza en el proceso de optimización para detener tempranamente las pruebas de los modelos cuando no se están obteniendo buenos resultados, basándose en su desempeño hasta ese momento. Es útil para cuando se están comparando muchos modelos y se busca encontrar los mejores hiperparámetros.

Impacta en el entramiento porque reduce su tiempo de entranamiento, evita el sobreajuste al no realizar iteracciones innecesarias y de esta forma se optimizan los recursos.

In [ ]:
import optuna
from optuna.integration import XGBoostPruningCallback

def objective(trial):
    # Sugerencias de hiperparámetros para XGBRegressor
    learning_rate = trial.suggest_float('learning_rate', 0.001, 0.1)
    n_estimators = trial.suggest_int('n_estimators', 50, 1000)
    max_depth = trial.suggest_int('max_depth', 3, 10)
    max_leaves = trial.suggest_int('max_leaves', 0, 100)
    min_child_weight = trial.suggest_int('min_child_weight', 1, 5)
    reg_alpha = trial.suggest_float('reg_alpha', 0.0, 1.0)
    reg_lambda = trial.suggest_float('reg_lambda', 0.0, 1.0)


    # Hiperparámetro del OneHotEncoder
    min_frequency = trial.suggest_float('min_frequency', 0.0, 1.0)

    # Ajuste del preprocesador (OneHotEncoder con min_frequency sugerido)
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numerical_columns),
            ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False, min_frequency=min_frequency), categorical_columns)
        ],
        remainder='passthrough'
    )

    # Crear el pipeline
    pipeline_xgb_optuna_prunner = Pipeline(steps=[
        ('preprocessor', preprocessor),
         ('regressor', XGBRegressor(
             random_state=seed,
             learning_rate=learning_rate,
             n_estimators=n_estimators,
             max_depth=max_depth,
            max_leaves=max_leaves,
            min_child_weight=min_child_weight,
            reg_alpha=reg_alpha,
            reg_lambda=reg_lambda
        ))
    ])

    # Entrenar el pipeline con los datos transformados y agregar el pruning callback
    pruning_callback = XGBoostPruningCallback(trial, "validation_0-mae")
    pipeline_xgb_optuna_prunner.fit(X_train_transformed, y_train)

    # Realizar predicciones en el conjunto de validación
    val_predictions_optuna_prunner = pipeline_xgb_optuna_prunner.predict(X_val_transformed)

    # Calcular el MAE
    mae = mean_absolute_error(y_val, val_predictions_optuna_prunner)

    # Almacenar el mejor pipeline en el trial utilizando set_user_attr
    trial.set_user_attr("best_pipeline", pipeline_xgb_optuna_prunner)

    return mae

In [ ]:
# 3. Fijar nuevamente el tiempo de entrenamiento a 5 minutos [1 punto]
study.optimize(objective, timeout=300)

[I 2024-10-24 23:50:57,673] Trial 139 finished with value: 2077.7754905303427 and parameters: {'learning_rate': 0.04488050572581134, 'n_estimators': 642, 'max_depth': 10, 'max_leaves': 86, 'min_child_weight': 5, 'reg_alpha': 0.42267576796691697, 'reg_lambda': 0.3924223168127448, 'min_frequency': 0.02038057914905607}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:50:59,689] Trial 140 finished with value: 2068.585181772311 and parameters: {'learning_rate': 0.05869812772838082, 'n_estimators': 690, 'max_depth': 10, 'max_leaves': 71, 'min_child_weight': 4, 'reg_alpha': 0.4732212508384608, 'reg_lambda': 0.4321219320669366, 'min_frequency': 0.054340557401213616}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:02,221] Trial 141 finished with value: 2083.2055636356286 and parameters: {'learning_rate': 0.0416082933872461, 'n_estimators': 807, 'max_depth': 10, 'max_leaves': 82, 'min_child_weight': 4, 'reg_alpha': 0.5863043952355497, 'reg_lambda': 0.26497529871364334, 'min_frequency': 0.02957621637899266}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:07,737] Trial 142 finished with value: 2110.338673732946 and parameters: {'learning_rate': 0.043168953714078424, 'n_estimators': 628, 'max_depth': 10, 'max_leaves': 92, 'min_child_weight': 4, 'reg_alpha': 0.5332960059143159, 'reg_lambda': 0.30218696371193055, 'min_frequency': 0.07157261048143782}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:09,851] Trial 143 finished with value: 3066.9815822137853 and parameters: {'learning_rate': 0.050309211483046144, 'n_estimators': 705, 'max_depth': 10, 'max_leaves': 98, 'min_child_weight': 4, 'reg_alpha': 0.6143483888636336, 'reg_lambda': 0.23484389146659584, 'min_frequency': 0.10224498669969262}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:11,958] Trial 144 finished with value: 2024.5679608944738 and parameters: {'learning_rate': 0.06168780042187574, 'n_estimators': 611, 'max_depth': 10, 'max_leaves': 88, 'min_child_weight': 4, 'reg_alpha': 0.5720326389502556, 'reg_lambda': 0.33451701964624236, 'min_frequency': 0.058887472255535034}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:14,079] Trial 145 finished with value: 2053.4000416897006 and parameters: {'learning_rate': 0.06233724448768815, 'n_estimators': 665, 'max_depth': 10, 'max_leaves': 87, 'min_child_weight': 4, 'reg_alpha': 0.5714905004234391, 'reg_lambda': 0.33204137074852474, 'min_frequency': 0.0383399385585977}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:15,440] Trial 146 finished with value: 7331.180889134732 and parameters: {'learning_rate': 0.060904975468617555, 'n_estimators': 614, 'max_depth': 10, 'max_leaves': 88, 'min_child_weight': 4, 'reg_alpha': 0.5626570945001604, 'reg_lambda': 0.36374071381923295, 'min_frequency': 0.6693916206724316}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:20,647] Trial 147 finished with value: 2928.1023346884385 and parameters: {'learning_rate': 0.0631436256728573, 'n_estimators': 666, 'max_depth': 10, 'max_leaves': 90, 'min_child_weight': 4, 'reg_alpha': 0.6033686423135856, 'reg_lambda': 0.3412259215814799, 'min_frequency': 0.08534671187395394}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:22,679] Trial 148 finished with value: 2065.8510820416805 and parameters: {'learning_rate': 0.06584101094680042, 'n_estimators': 645, 'max_depth': 10, 'max_leaves': 86, 'min_child_weight': 4, 'reg_alpha': 0.5705107930918168, 'reg_lambda': 0.3255781051140209, 'min_frequency': 0.04221638905085994}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:24,374] Trial 149 finished with value: 3017.0757148854723 and parameters: {'learning_rate': 0.053915948720089577, 'n_estimators': 601, 'max_depth': 10, 'max_leaves': 81, 'min_child_weight': 4, 'reg_alpha': 0.5425618712829717, 'reg_lambda': 0.2899469646507279, 'min_frequency': 0.12983343110515053}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:26,718] Trial 150 finished with value: 2072.075575865477 and parameters: {'learning_rate': 0.06910068146346411, 'n_estimators': 678, 'max_depth': 10, 'max_leaves': 96, 'min_child_weight': 4, 'reg_alpha': 0.6225076581261533, 'reg_lambda': 0.27472066481836416, 'min_frequency': 0.05996060443195621}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:28,824] Trial 151 finished with value: 3063.7967778652787 and parameters: {'learning_rate': 0.05589541038120001, 'n_estimators': 733, 'max_depth': 10, 'max_leaves': 91, 'min_child_weight': 4, 'reg_alpha': 0.5116984977866509, 'reg_lambda': 0.31104378579261455, 'min_frequency': 0.10207132689383577}. Best is trial 131 with value: 2021.2459897702145.
[I 2024-10-24 23:51:34,038] Trial 152 finished with value: 2005.191900887381 and parameters: {'learning_rate': 0.06677150149934513, 'n_estimators': 635, 'max_depth': 10, 'max_leaves': 86, 'min_child_weight': 4, 'reg_alpha': 0.5834353753193662, 'reg_lambda': 0.33299873753799236, 'min_frequency': 0.04000009635282412}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:36,173] Trial 153 finished with value: 2088.3420253697636 and parameters: {'learning_rate': 0.060289528908590205, 'n_estimators': 657, 'max_depth': 10, 'max_leaves': 87, 'min_child_weight': 4, 'reg_alpha': 0.5901981131749893, 'reg_lambda': 0.3567242413511004, 'min_frequency': 0.03578653672202809}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:38,173] Trial 154 finished with value: 2074.993376259492 and parameters: {'learning_rate': 0.06312552685816379, 'n_estimators': 629, 'max_depth': 10, 'max_leaves': 84, 'min_child_weight': 4, 'reg_alpha': 0.5497945666626805, 'reg_lambda': 0.380372888306914, 'min_frequency': 0.01855047927784465}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:43,831] Trial 155 finished with value: 2056.161538464046 and parameters: {'learning_rate': 0.06672010745248015, 'n_estimators': 591, 'max_depth': 10, 'max_leaves': 78, 'min_child_weight': 4, 'reg_alpha': 0.6432748526231328, 'reg_lambda': 0.33291167739161, 'min_frequency': 0.06289574848705826}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:48,219] Trial 156 finished with value: 7322.484648313637 and parameters: {'learning_rate': 0.06639898416945242, 'n_estimators': 590, 'max_depth': 10, 'max_leaves': 78, 'min_child_weight': 4, 'reg_alpha': 0.6567828674850283, 'reg_lambda': 0.3361010543981664, 'min_frequency': 0.401402911186696}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:50,263] Trial 157 finished with value: 2066.2011262412384 and parameters: {'learning_rate': 0.07016123631698676, 'n_estimators': 615, 'max_depth': 10, 'max_leaves': 88, 'min_child_weight': 4, 'reg_alpha': 0.5998696307257677, 'reg_lambda': 0.31382573524440033, 'min_frequency': 0.07056583028363775}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:52,396] Trial 158 finished with value: 2054.8956486252505 and parameters: {'learning_rate': 0.07247525638421858, 'n_estimators': 641, 'max_depth': 10, 'max_leaves': 94, 'min_child_weight': 4, 'reg_alpha': 0.6479751685866889, 'reg_lambda': 0.34748467738637495, 'min_frequency': 0.07949024615908303}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:54,319] Trial 159 finished with value: 2354.719393273062 and parameters: {'learning_rate': 0.07222146820604296, 'n_estimators': 591, 'max_depth': 10, 'max_leaves': 94, 'min_child_weight': 4, 'reg_alpha': 0.6386010924836578, 'reg_lambda': 0.40099693425344596, 'min_frequency': 0.08288313706017975}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:55,920] Trial 160 finished with value: 3067.4780522793412 and parameters: {'learning_rate': 0.06770684188831919, 'n_estimators': 552, 'max_depth': 10, 'max_leaves': 83, 'min_child_weight': 4, 'reg_alpha': 0.6451161400595222, 'reg_lambda': 0.4217855897237644, 'min_frequency': 0.1115867975075534}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:51:57,052] Trial 161 finished with value: 2881.5246265243304 and parameters: {'learning_rate': 0.07384304798186828, 'n_estimators': 640, 'max_depth': 10, 'max_leaves': 29, 'min_child_weight': 4, 'reg_alpha': 0.6235739713832167, 'reg_lambda': 0.3533408083472296, 'min_frequency': 0.14453367278605972}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:02,436] Trial 162 finished with value: 2043.2796021322702 and parameters: {'learning_rate': 0.06382142681288322, 'n_estimators': 659, 'max_depth': 10, 'max_leaves': 92, 'min_child_weight': 4, 'reg_alpha': 0.5271215714772136, 'reg_lambda': 0.3264506519554575, 'min_frequency': 0.057582787924867186}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:04,527] Trial 163 finished with value: 2074.324686170102 and parameters: {'learning_rate': 0.06401025881323505, 'n_estimators': 614, 'max_depth': 10, 'max_leaves': 98, 'min_child_weight': 4, 'reg_alpha': 0.5273257628181814, 'reg_lambda': 0.37520528927691293, 'min_frequency': 0.062317021568825036}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:06,706] Trial 164 finished with value: 2066.324312136234 and parameters: {'learning_rate': 0.06178848379955545, 'n_estimators': 657, 'max_depth': 10, 'max_leaves': 93, 'min_child_weight': 4, 'reg_alpha': 0.5672702166597731, 'reg_lambda': 0.3308941732797012, 'min_frequency': 0.021638714944392172}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:08,636] Trial 165 finished with value: 3067.3848841098024 and parameters: {'learning_rate': 0.06619324479278792, 'n_estimators': 630, 'max_depth': 10, 'max_leaves': 96, 'min_child_weight': 4, 'reg_alpha': 0.5508624016380511, 'reg_lambda': 0.2933117286144662, 'min_frequency': 0.09046170839834837}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:14,722] Trial 166 finished with value: 2038.1014052265 and parameters: {'learning_rate': 0.058241797391567894, 'n_estimators': 942, 'max_depth': 10, 'max_leaves': 89, 'min_child_weight': 4, 'reg_alpha': 0.6010736203615201, 'reg_lambda': 0.34000131548964996, 'min_frequency': 0.05932627038920027}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:17,944] Trial 167 finished with value: 2060.893348357706 and parameters: {'learning_rate': 0.057793752985916845, 'n_estimators': 949, 'max_depth': 10, 'max_leaves': 100, 'min_child_weight': 4, 'reg_alpha': 0.6615923045585678, 'reg_lambda': 0.34399950654722583, 'min_frequency': 0.019775558873227166}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:20,781] Trial 168 finished with value: 2035.5869976700706 and parameters: {'learning_rate': 0.06864517827232004, 'n_estimators': 900, 'max_depth': 10, 'max_leaves': 90, 'min_child_weight': 4, 'reg_alpha': 0.602730784621266, 'reg_lambda': 0.3882262176017421, 'min_frequency': 0.07665185218172642}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:23,717] Trial 169 finished with value: 2053.6911360329395 and parameters: {'learning_rate': 0.06960736252311084, 'n_estimators': 969, 'max_depth': 10, 'max_leaves': 89, 'min_child_weight': 4, 'reg_alpha': 0.6246528549127304, 'reg_lambda': 0.3937847831806964, 'min_frequency': 0.07433103015635033}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:29,528] Trial 170 finished with value: 3087.7988224207797 and parameters: {'learning_rate': 0.0706697435620667, 'n_estimators': 967, 'max_depth': 10, 'max_leaves': 90, 'min_child_weight': 4, 'reg_alpha': 0.6132595379330704, 'reg_lambda': 0.4680328017342963, 'min_frequency': 0.1199274887805308}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:32,088] Trial 171 finished with value: 2981.0806224705857 and parameters: {'learning_rate': 0.06804689119053978, 'n_estimators': 911, 'max_depth': 10, 'max_leaves': 88, 'min_child_weight': 4, 'reg_alpha': 0.5937738796050929, 'reg_lambda': 0.4044280126165036, 'min_frequency': 0.08538397832018205}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:35,053] Trial 172 finished with value: 2078.8459435171376 and parameters: {'learning_rate': 0.07566434071534547, 'n_estimators': 928, 'max_depth': 10, 'max_leaves': 93, 'min_child_weight': 4, 'reg_alpha': 0.6290763265736513, 'reg_lambda': 0.3844613563518139, 'min_frequency': 0.07061247091071747}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:37,175] Trial 173 finished with value: 7579.351529741478 and parameters: {'learning_rate': 0.06530038542040503, 'n_estimators': 990, 'max_depth': 10, 'max_leaves': 90, 'min_child_weight': 4, 'reg_alpha': 0.6731901409326014, 'reg_lambda': 0.3714586966906603, 'min_frequency': 0.5054840139032402}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:43,448] Trial 174 finished with value: 2016.652006386119 and parameters: {'learning_rate': 0.06950266922412077, 'n_estimators': 973, 'max_depth': 10, 'max_leaves': 94, 'min_child_weight': 4, 'reg_alpha': 0.6478208584750692, 'reg_lambda': 0.42529366349430864, 'min_frequency': 0.040153353204672323}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:46,480] Trial 175 finished with value: 2076.6117259536154 and parameters: {'learning_rate': 0.06914796663502204, 'n_estimators': 874, 'max_depth': 10, 'max_leaves': 95, 'min_child_weight': 4, 'reg_alpha': 0.5766124631525745, 'reg_lambda': 0.45562315765681705, 'min_frequency': 0.03589876082666513}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:49,624] Trial 176 finished with value: 2074.4160299670393 and parameters: {'learning_rate': 0.06337606110960181, 'n_estimators': 941, 'max_depth': 10, 'max_leaves': 92, 'min_child_weight': 4, 'reg_alpha': 0.735730829752295, 'reg_lambda': 0.42521696862463365, 'min_frequency': 0.041836824070095535}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:55,822] Trial 177 finished with value: 2056.26744660198 and parameters: {'learning_rate': 0.06975288941252902, 'n_estimators': 963, 'max_depth': 10, 'max_leaves': 89, 'min_child_weight': 4, 'reg_alpha': 0.6181626589192252, 'reg_lambda': 0.4013362229539355, 'min_frequency': 0.0015223196000101029}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:52:58,415] Trial 178 finished with value: 3058.507877691088 and parameters: {'learning_rate': 0.0651835982503733, 'n_estimators': 894, 'max_depth': 10, 'max_leaves': 96, 'min_child_weight': 4, 'reg_alpha': 0.6009784210145916, 'reg_lambda': 0.3610931986083707, 'min_frequency': 0.10289450469081735}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:01,572] Trial 179 finished with value: 2019.4760813897697 and parameters: {'learning_rate': 0.07832640505782543, 'n_estimators': 987, 'max_depth': 10, 'max_leaves': 92, 'min_child_weight': 4, 'reg_alpha': 0.5804391694560567, 'reg_lambda': 0.3914132228716656, 'min_frequency': 0.021125247783704268}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:06,085] Trial 180 finished with value: 2028.4478631013226 and parameters: {'learning_rate': 0.07812357767072614, 'n_estimators': 982, 'max_depth': 10, 'max_leaves': 93, 'min_child_weight': 4, 'reg_alpha': 0.6562850611064585, 'reg_lambda': 0.4126412642373444, 'min_frequency': 0.018894697376887495}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:10,745] Trial 181 finished with value: 2066.2289537091124 and parameters: {'learning_rate': 0.07726569234114493, 'n_estimators': 1000, 'max_depth': 10, 'max_leaves': 92, 'min_child_weight': 4, 'reg_alpha': 0.5821980501572177, 'reg_lambda': 0.4204058351495536, 'min_frequency': 0.021560647488009316}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:13,850] Trial 182 finished with value: 2121.0794865158755 and parameters: {'learning_rate': 0.07309211852239893, 'n_estimators': 976, 'max_depth': 10, 'max_leaves': 94, 'min_child_weight': 4, 'reg_alpha': 0.6461203357501247, 'reg_lambda': 0.3840177251567326, 'min_frequency': 0.03754039857443503}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:16,963] Trial 183 finished with value: 2098.574477395642 and parameters: {'learning_rate': 0.07531726333655693, 'n_estimators': 959, 'max_depth': 10, 'max_leaves': 97, 'min_child_weight': 4, 'reg_alpha': 0.6692051070684684, 'reg_lambda': 0.44326391273249505, 'min_frequency': 0.012194742644500597}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:23,262] Trial 184 finished with value: 2093.015945414198 and parameters: {'learning_rate': 0.07079373696994246, 'n_estimators': 979, 'max_depth': 10, 'max_leaves': 91, 'min_child_weight': 4, 'reg_alpha': 0.689133623908547, 'reg_lambda': 0.48800006467831164, 'min_frequency': 0.05208248549847081}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:26,218] Trial 185 finished with value: 2082.5231405545937 and parameters: {'learning_rate': 0.0715632912991835, 'n_estimators': 935, 'max_depth': 10, 'max_leaves': 94, 'min_child_weight': 4, 'reg_alpha': 0.6233322195134243, 'reg_lambda': 0.39092541123694374, 'min_frequency': 0.026093442189797072}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:29,102] Trial 186 finished with value: 2060.9540668482455 and parameters: {'learning_rate': 0.07772448411422994, 'n_estimators': 947, 'max_depth': 10, 'max_leaves': 88, 'min_child_weight': 4, 'reg_alpha': 0.6055376737906822, 'reg_lambda': 0.3602607436036037, 'min_frequency': 0.001794100182195467}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:35,422] Trial 187 finished with value: 2070.6564952814692 and parameters: {'learning_rate': 0.07882269366192843, 'n_estimators': 983, 'max_depth': 10, 'max_leaves': 99, 'min_child_weight': 4, 'reg_alpha': 0.5658675384749721, 'reg_lambda': 0.4177796463319098, 'min_frequency': 0.049780882739762986}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:38,117] Trial 188 finished with value: 2027.9221002352094 and parameters: {'learning_rate': 0.06782211909029123, 'n_estimators': 906, 'max_depth': 10, 'max_leaves': 86, 'min_child_weight': 4, 'reg_alpha': 0.7044672825719348, 'reg_lambda': 0.3480541859737454, 'min_frequency': 0.0772443169261055}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:40,851] Trial 189 finished with value: 2032.1227862736253 and parameters: {'learning_rate': 0.0681953112668668, 'n_estimators': 900, 'max_depth': 10, 'max_leaves': 85, 'min_child_weight': 4, 'reg_alpha': 0.7327413925227612, 'reg_lambda': 0.09749544217123518, 'min_frequency': 0.03203508968319558}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:43,630] Trial 190 finished with value: 2051.336447131331 and parameters: {'learning_rate': 0.0675486963005475, 'n_estimators': 904, 'max_depth': 10, 'max_leaves': 85, 'min_child_weight': 4, 'reg_alpha': 0.726689510064039, 'reg_lambda': 0.050098443659749164, 'min_frequency': 0.028984619818347192}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:49,580] Trial 191 finished with value: 2090.22153740795 and parameters: {'learning_rate': 0.06385587904332783, 'n_estimators': 890, 'max_depth': 10, 'max_leaves': 85, 'min_child_weight': 4, 'reg_alpha': 0.712751311177002, 'reg_lambda': 0.05158750365857552, 'min_frequency': 0.021997764660291793}. Best is trial 152 with value: 2005.191900887381.
[I 2024-10-24 23:53:52,439] Trial 192 finished with value: 2054.505364737619 and parameters: {'learning_rate': 0.06818755193324784, 'n_estimators': 935, 'max_depth': 10, 'max_leaves': 87, 'min_child_weight': 4, 'reg_alpha': 0.7610152408540819, 'reg_lambda': 0.0007944021311969696, 'min_frequency': 0.035941633092130304}. Best is trial 152 with value: 2005.191900887381.

In [ ]:
# 4. Reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
print(f'Número de trials: {len(study.trials)}')
print(f'Mejor MAE obtenido: {study.best_value}')
print(f'Mejores hiperparámetros: {study.best_params}')

Número de trials: 229
Mejor MAE obtenido: 2000.9103635576603
Mejores hiperparámetros: {'learning_rate': 0.06735520736182712, 'n_estimators': 889, 'max_depth': 10, 'max_leaves': 84, 'min_child_weight': 4, 'reg_alpha': 0.8198420225145645, 'reg_lambda': 0.05701224506872668, 'min_frequency': 0.020194403319583366}

*   **Optuna:**
```
Número de trials: 124
Mejor MAE obtenido: 2039.4655323308682
Mejores hiperparámetros: {'learning_rate': 0.06258057837647998, 'n_estimators': 800,
'max_depth': 10, 'max_leaves': 78, 'min_child_weight': 4, 'reg_alpha': 0.7627014672965421,
'reg_lambda': 0.2529218490083219, 'min_frequency': 0.011606578881046742}
```
*   **Optuna y Prunning:**
```
Número de trials: 202
Mejor MAE obtenido: 2008.5927721336782
Mejores hiperparámetros: {'learning_rate': 0.06737610202159762, 'n_estimators': 1000,
'max_depth': 10, 'max_leaves': 84, 'min_child_weight': 4, 'reg_alpha': 0.1968005888173449,
'reg_lambda': 0.21615935883382276, 'min_frequency': 0.0204794515229899}
```

El nuevo **MAE** con Optuna y Prunning es de **2008.59**, siendo levemente menor que en la sección anterior, esta mejora muestra un ajuste más preciso de los hiperparámetros al incluir la **Prunning**, que permite detener los trials que no presentan una mejora clara, optimizando así su tiempo de entrenamiento.

El número **trials** aumentó a **202**, este aumento se debe a que, al eliminar combinaciones menos efectivas durante el entrenamiento del modelo, Optuna logra explorar más configuraciones en un tiempo similar que a la sección anterior, teniendo más oportunidades de encontrar una combinación de hiperparámetros mejor.

Los **hiperparámetros** son similares en los dos modelos. Se ve un cambio significativo en `reg_alpha`, que disminuyó de **0.7627** a **0.1968**, que indica menos penalización en los coeficientes, permitiendo que el modelo se ajuste mejor a nuestros datos.

In [ ]:
# 5. Guardar su modelo en un archivo .pkl [1 punto]
best_pipeline_prunning = study.best_trial.user_attrs["best_pipeline"]
joblib.dump(best_pipeline_prunning, 'xgb_regressor_optuna_prunning_best_pipeline.pkl')

print("Mejor pipeline guardado correctamente.")

Mejor pipeline guardado correctamente.

## 5. Visualizaciones (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/F-LgB1xTebEAAAAd/look-at-this-graph-nickelback.gif">
</p>


Satisfecho con su trabajo, Fiu le pregunta si es posible generar visualizaciones que permitan entender el entrenamiento de su modelo.

A partir del siguiente <a href = https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/005_visualization.html#visualization>enlace</a>, genere las siguientes visualizaciones:

1. Gráfico de historial de optimización [1 punto]
2. Gráfico de coordenadas paralelas [1 punto]
3. Gráfico de importancia de hiperparámetros [1 punto]

Comente sus resultados:

4. ¿Desde qué *trial* se empiezan a observar mejoras notables en sus resultados? [0.5 puntos]
5. ¿Qué tendencias puede observar a partir del gráfico de coordenadas paralelas? [1 punto]
6. ¿Cuáles son los hiperparámetros con mayor importancia para la optimización de su modelo? [0.5 puntos]

In [ ]:
!pip install plotly

In [ ]:
#1. Gráfico de historial de optimización [1 punto]
import optuna.visualization as vis

vis.plot_optimization_history(study)

In [ ]:
#2. Gráfico de coordenadas paralelas [1 punto]
vis.plot_parallel_coordinate(study)

In [ ]:
#3. Gráfico de importancia de hiperparámetros [1 punto]
vis.plot_param_importances(study)

**¿Desde qué trial se empiezan a observar mejoras notables en sus resultados?**

Del **Gráfico de historial de optimización**, se observa que las mejoras notables se empiezan a observar desde los primers trials, se podría decir que desde el 13 aproximadamente, donde el valor objetivo (`mae`) empieza a caer notablemente para luego mantenerse cerca del 2.000.

**¿Qué tendencias puede observar a partir del gráfico de coordenadas paralelas?**

Del **Gráfico de coordenadas paralelas** se puede observar que el hiperparámetro `min_frequency` tiene una fuerte correlación con los resultados, de manera similar ocurre con `reg_lambda` y `n_estimators` pero no tan fuerte como con el anterior.

**¿Cuáles son los hiperparámetros con mayor importancia para la optimización de su modelo?**

Del **Gráfico de importancia de hiperparámetros** se observa que el hiperparámetro `min_frequency` es el más importante para la optimización del modelo, con una importancia del 85%. Luego, siguen ``reg_lambda` y `n_estimators` con 7% y 4%, respectivamente, similiar a la conslusión anterior.

## 6. Síntesis de resultados (3 puntos)

Finalmente:

1. Genere una tabla resumen del MAE en el conjunto de validación obtenido en los 5 modelos entrenados desde Baseline hasta XGBoost con Constraints, Optuna y Prunning. [1 punto]
2. Compare los resultados de la tabla y responda, ¿qué modelo obtiene el mejor rendimiento? [0.5 puntos]
3. Cargue el mejor modelo, prediga sobre el conjunto de **test** y reporte su MAE. [0.5 puntos]
4. ¿Existen diferencias con respecto a las métricas obtenidas en el conjunto de validación? ¿Porqué puede ocurrir esto? [1 punto]

In [ ]:
mae_xgb_optuna = mean_absolute_error(y_val, best_pipeline.predict(X_val_transformed))
mae_xgb_pruning = mean_absolute_error(y_val, best_pipeline_prunning.predict(X_val_transformed))

MAE XGBoost con Optuna: 2021.2459897702145
MAE XGBoost con Prunning: 2000.9103635576603

In [ ]:
mae_xgb_optuna = mean_absolute_error(y_val, best_pipeline.predict(X_val_transformed))
mae_xgb_pruning = mean_absolute_error(y_val, best_pipeline_prunning.predict(X_val_transformed))

mae_tabla = {
    'Modelo': ['Baseline', 'XGBoost', 'XGBoost con Restricciones Monótonas', 'XGBoost con Optuna', 'XGBoost con Optuna y Prunning'],
    'MAE': [mae, mae_xgb, mae_xgb_monotonic, mae_xgb_optuna, mae_xgb_pruning]
}
mae_tabla = pd.DataFrame(mae_tabla)
mae_tabla

                                Modelo           MAE
0                             Baseline  13308.134751
1                              XGBoost   2402.188326
2  XGBoost con Restricciones Monótonas   2493.647739
3                   XGBoost con Optuna   2021.245990
4        XGBoost con Optuna y Prunning   2000.910364

De la tabla, se puede observar que el modelo que tiene mejor rendimiento es el **XGBoost con Optuna y Prunning** con un **MAE** de **2000.91**

In [ ]:
# 2. Predecir sobre el conjunto de test
X_test_transformed = date_transformer.transform(X_test.copy())

# Predecir sobre el conjunto de test
test_predictions = best_pipeline_prunning.predict(X_test_transformed)

# Calcular el MAE en el conjunto de test
mae_test = mean_absolute_error(y_test, test_predictions)

print(f'MAE en el conjunto de test: {mae_test}')

MAE en el conjunto de test: 2123.9053279479235

**¿Existen diferencias con respecto a las métricas obtenidas en el conjunto de validación? ¿Porqué puede ocurrir esto?**

El MAE en el **conjunto de test** fue de **2123.90**, mientras que en el **conjunto de validación** fue de **2000.91**, esto se puede deber a varias razones, como la distribución de los datos, el tamaño que se utilizó para definir los conjuntos de entrenamiento, test y validación. Esta diferencia es "normal" en estas situaciones, por último, la diferencia no es relativamente grande y podría estar bien de acuerdo a las razones dadas anteriormente.

# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media.tenor.com/8CT1AXElF_cAAAAC/gojo-satoru.gif">
</p>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>